### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by random-person-001** [random-person-001/MagicText#24]
Jared thinks that this (high CPU usage for a text game) is a problem. (personally, I'm more concerned with getting it working, but whatevs)

Percentage of my CPU the game takes up:
![image](https://cloud.githubusercontent.com/assets/14933641/19840573/e8dd5b2c-9ec6-11e6-9065-00b2383f6e34.png)

**Comment by zachllogan** [comment]
I think high CPU usage is a concern, but I'm not completely convinced the game has high CPU usage. I only see 1(perhaps 2) spike where the graph goes to unreasonable levels. Are these spikes frequent or are they uncommon or perhaps that one was a coincidence. Also, were other programs running, because I think the real test is whether the game or other programs suffer in performance (or CPU maxes out) while the game and other programs are running, rather than a simple graph.

**Comment by random-person-001** [comment]
The data taken reflect(s) just the MagicText process, not the total cpu usage.  (I used `top -p [PID returned by java -jar MagicText.jar & disown]` in appropriate directory on a loop with some formatting stuff ([script here](https://gist.github.com/random-person-001/da4ac5b54996ca3af6dba0f579b7ba5d)) to get just the cpu output, and pasted the cpu usages to a LibreOffice calc spreadsheet.  Overkill, I know, but automating it was fun).

I'd have to look again at how often the spikes are, I didn't record that very thoroughly.

Jared's goal I think is more of a philosophical one, that a text game should have very low resource usage.

**Comment by random-person-001** [comment]
I took the data again - it looks like there's a sizable baseline of around 15% with typical addons of another 10% in some levels.  The snowy peak, with lots of snowflake layers, takes up more resources.

What I'm really surprised about is the amount of CPU usage on the title screen (where the first three data points are).

![image](https://cloud.githubusercontent.com/assets/14933641/19913932/ca269856-a074-11e6-92d0-c4d85f428975.png)

**Comment by zachllogan** [comment]
My CPU usage, while high, was lower than yours, but perhaps my processor is faster.

![usage1](https://cloud.githubusercontent.com/assets/22415468/19948685/e43760c0-a11b-11e6-84b9-0ddd1ae4f565.PNG)
with normal programs running

![usage lowtotalcpu](https://cloud.githubusercontent.com/assets/22415468/19948691/ec934220-a11b-11e6-9718-9a4d8a6712ed.PNG)
with few programs running

![usage hightotalcpu](https://cloud.githubusercontent.com/assets/22415468/19948696/f5ce7238-a11b-11e6-81dd-df0cc0db69f4.PNG)
with stress tester running

With a stress tester running CPU usage was somewhat decreased (often about half; I know it does look like it but I was mostly in snow area), so it isn't necessarily as much of a CPU hog as we though; however, I did have some lag when in the snowy area. Compared to the usage of other programs it does have REALLY high CPU usage so perhaps it is a problem. For benchmark here is the CPU usage of a couple of other programs:

![intellij](https://cloud.githubusercontent.com/assets/22415468/19949261/acd8f82a-a11e-11e6-9fb9-1acd5b5a8049.PNG)
IntelliJ

![mastermindcpuusage](https://cloud.githubusercontent.com/assets/22415468/19949273/bb31ed28-a11e-11e6-8f3c-0a6fd5872e17.PNG)
MasterMind program I made last year for class

Also note the red area, that is kernel mode CPU usage, which we generally want to avoid (switching between kernel & user is slow & kernel can cause blue-screens (though probably not a problem because I think I know what is causing it)). MagicText not only uses more CPU, but also uses a higher percent kernel mode.

I have some ideas how to fix this, which I will try over the next few days (or maybe week?)

**Comment by random-person-001** [comment]
This is after I switched window resizing variables to be recalculated only on window resize rather than each time it repainted in 2aca83b50ce837b875c40ab490771a71a605186e.  The data is still noisy :cry: but (compared to the former measurements) it's at least below 10% most of the time.

![image](https://cloud.githubusercontent.com/assets/14933641/20469674/469bbb04-af67-11e6-86e3-d1db62f226eb.png)

**Comment by random-person-001** [comment]
426de0892ddddf47afe34a2cda57bb3bbbb75536 also reduced CPU by calling repaint() roughly half as often - on Window.build() rather than on its own timer.  (I don't know any quantities re: how much less).

**Comment by random-person-001** [comment]
I think we have a good handle on this now, I'll close this issue unless there are any objections.
