### ISSUE TITLE
Legit Room constructor?

### ISSUE THREAD

**Issue by random-person-001** [random-person-001/MagicText#7]
I made a method in Room.java called `constructor(Player player)` which is only called in the (unnessessary?) constructors of the classes which extend it.  Is there a way to make that more legit Java code / will you?

**Comment by random-person-001** [comment]
Hey @zachllogan , can you do this?
When done, you can probably come to this issue on Github and mark it as "closed."  To be really fancy, mention "#7" in your commit message of the code :sunglasses: to let posterity know which commit resolved this.

If you have questions about the IDE or anything, feel free to ask us!  (btw, this isn't urgent, just a thing when you have time)

**Comment by zachllogan** [comment]
Yeah, I'll check it out some time soon(ish, maybe).

**Comment by zachllogan** [comment]
I got to it tonight, but want verification that my changes didn't break the game before closing.

**Comment by zachllogan** [comment]
I cleaned up those constructors. 

@random-person-001 @HazilTheNut Some tips for future reference: 
1. Constructors should always be the very first method in the class; I usually put it below variable initialization, but above would probably be ok too.
2. constructors should be formatted properly: there is no type declaration and the name needs to be exactly the same as the class it is for (protected Room(Player player) instead of protected void constructor(Player player)).
3. I noticed some (pointless I think) redundant seeming declarations, specifically imageorganizer org was declared in both room and some of its sub classes and the same code in both the superclass constructor and the subclass constructor, like index=1 (there were a couple other things as well).  Extending a class basically copy-and-pastes the super classes code into the subclass for adding additions (of course its actually more complicated, It wont quite work that way if the superclass is static I think?) so there is no need to define a variable in both the super and sub class unless they explicitly need to hold different values.
4. Not important, but just so you know the keyword super doesn't have to be used to refer to variables or methods of the superclass unless the subclass also contains the same variables. Some people like to always use super, however, for clarity. I personally usually only use super when it is needed, but I don't really care. I think the key is to remain consistent, so we should decide on one way or the other.

Are there any other areas that you want cleaned or organized?

**Comment by random-person-001** [comment]
Thanks Zach!  
I think the index variable served a similar purpose to strRoomName back when the game was a bit more linear.  Now it's completely obsolete.
The usage of the super keyword is probably also superfluous junk - we are obviously not the people to be preaching coding style 😝 , so that wasn't intentional.   (I'm not emotionally attached to any of that junk, so if anyone removed it, it wouldn't hurt my heart)
